name: Stock Scraper

on:
  schedule:
    - cron: '20 12 * * *'  # 9:20 AM BRT
    - cron: '0 16 * * *'   # 1:00 PM BRT
    - cron: '30 21 * * *'  # 6:30 PM BRT
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install ChromeDriver
      uses: browser-actions/setup-chrome@v2
      with:
        install-chromedriver: true

    - name: Install OpenVPN
      run: |
        sudo apt update
        sudo apt install -y openvpn
        
        # Write config file
        echo "${{ secrets.OPENVPN_CONFIG }}" > config.ovpn
        
        # Create password file
        echo "${{ secrets.OPENVPN_PASSWORD }}" > pass.txt
        chmod 600 config.ovpn pass.txt

    - name: Connect to VPN with logging
      run: |
        sudo openvpn \
          --config config.ovpn \
          --auth-user-pass pass.txt \
          --daemon \
          --log openvpn.log \
          --writepid openvpn.pid
        
        echo "Waiting for VPN connection..."
        for i in {1..30}; do
          if grep -q "Initialization Sequence Completed" openvpn.log; then
            echo "VPN connection established!"
            break
          fi
          sleep 1
        done
        
        if ! grep -q "Initialization Sequence Completed" openvpn.log; then
          echo "❌ VPN failed to connect within 30 seconds"
          echo "=== OpenVPN Log ==="
          cat openvpn.log
          exit 1
        fi
        
        # Verify public IP
        echo "Current public IP:"
        curl --max-time 5 ifconfig.me
        echo -e "\nVPN setup complete"

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python src/scraper.py

    - name: Terminate OpenVPN
      if: always()
      run: |
        if [ -f openvpn.pid ]; then
          sudo kill $(cat openvpn.pid) || echo "OpenVPN already stopped"
        fi
        rm -f config.ovpn pass.txt openvpn.log openvpn.pid