name: Stock Scraper

on:
  schedule:
    - cron: '20 12 * * *'  # 9:20 AM BRT = 12:20 PM UTC
    - cron: '0 16 * * *'   # 1:00 PM BRT = 4:00 PM UTC
    - cron: '30 21 * * *'  # 6:30 PM BRT = 9:30 PM UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install selenium webdriver-manager mysql-connector-python

    - name: Verify installations
      run: |
        google-chrome --version
        chromedriver --version
        python -c "import selenium; print(f'Selenium {selenium.__version__}')"

    - name: Run Python script
      run: python src/scraper.py