name: Stock Scraper

on:
  schedule:
    - cron: '20 12 * * *'  # 9:20 AM BRT
    - cron: '0 16 * * *'   # 1:00 PM BRT
    - cron: '30 21 * * *'  # 6:30 PM BRT
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Latest Chrome
      run: |
        # Install dependencies
        sudo apt-get update
        sudo apt-get install -y wget unzip libxss1 libappindicator1 libindicator7 fonts-liberation
        
        # Download and install latest stable Chrome
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -fy install
        
        # Verify installation
        google-chrome --version
        which google-chrome

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"

    - name: Verify versions
      run: |
        echo "=== Version Information ==="
        google-chrome --version
        python -c "import chromedriver_autoinstaller as c; print(f'ChromeDriver: {c.get_chrome_version()}')"

    - name: Run scraper
      run: |
        python src/scraper.py