name: Stock Scraper

on:
  schedule:
    - cron: '20 12 * * *'  # 9:20 AM BRT
    - cron: '0 16 * * *'   # 1:00 PM BRT
    - cron: '30 21 * * *'  # 6:30 PM BRT
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install ChromeDriver
      uses: browser-actions/setup-chrome@v2
      with:
          chrome-version: 138
          install-chromedriver: true

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python src/scraper.py
