name: Stock Scraper

on:
  schedule:
    - cron: '20 12 * * *'  # 9:20 AM BRT
    - cron: '0 16 * * *'   # 1:00 PM BRT
    - cron: '30 21 * * *'  # 6:30 PM BRT
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install ChromeDriver
      uses: browser-actions/setup-chrome@v2
      with:
          install-chromedriver: true
    - name: Install OpenVPN
      run: |
        sudo apt update
        sudo apt install -y openvpn openvpn-systemd-resolved

        echo "${{ secrets.OPENVPN_CONFIG }}" > config.ovpn
        
    - name: Connect to VPN
      uses: "kota65535/github-openvpn-connect-action@v3.1.0"
      with:
        config_file: config.ovpn
        password: ${{ secrets.OPENVPN_PASSWORD }}

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python src/scraper.py