name: Stock Scraper

on:
  schedule:
    - cron: '20 12 * * *'  # 9:20 AM BRT
    - cron: '0 16 * * *'   # 1:00 PM BRT
    - cron: '30 21 * * *'  # 6:30 PM BRT
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Chrome (required for Selenium)
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest-stable'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install selenium chromedriver-autoinstaller webdriver-manager mysql-connector-python

    - name: Verify installations
      run: |
        google-chrome --version
        python -c "import selenium; print(f'Selenium {selenium.__version__}')"
        python -c "import chromedriver_autoinstaller; print('chromedriver-autoinstaller available')"

    - name: Run scraper
      run: python src/scraper.py