name: Stock Scraper

on:
  schedule:
    - cron: '20 12 * * *'  # 9:20 AM BRT
    - cron: '0 16 * * *'   # 1:00 PM BRT
    - cron: '30 21 * * *'  # 6:30 PM BRT
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"

    - name: Verify installations
      run: |
        python -c "import chromedriver_autoinstaller as c; print(f'ChromeDriver: {c.get_chrome_version()}')"
        pip list

    - name: Run scraper
      run: |
        pwd
        ls -lR
        python src/scraper.py